VERSION=7.0.0-alpha01
ARTIFACT=mapp-android
DEVELOPER_NAME=Mapp
LICENSE_URL=https://github.com/mapp-digital/mapp-engage-android-v7/blob/main/LICENSE.md
SITE_URL=https://mapp.com
LICENSE_NAME=MIT License
GIT_URL=https://github.com/mapp-digital/mapp-engage-android-v7
BINTRAY_REPO=mapp-android
LIBRARY_NAME=mapp-android
DEVELOPER_EMAIL=aleksandar.marinkovic@mapp.com
LIBRARY_DESCRIPTION=Mapp Android SDK
DEVELOPER_ID=Mapp
PUBLISHED_GROUP_ID=com.mapp.sdk
BINRTAY_NAME=mapp-android
POM_URL=https://github.com/mapp-digital/mapp-engage-android-v7
POM_SCM_URL=https://github.com/mapp-digital/mapp-engage-android-v7
POM_SCM_CONNECTION=scm:git:https://github.com/mapp-digital/mapp-engage-android-v7
POM_SCM_DEV_CONNECTION=scm:git:https://github.com/mapp-digital/mapp-engage-android-v7