################
GROUP=com.mapp.sdk
POM_ARTIFACT_ID=engage-android
VERSION_NAME=7.0.0-beta05

POM_NAME=Mapp Engage Android SDK
POM_DESCRIPTION=The Mapp Engage Android SDK (v7)
POM_INCEPTION_YEAR=2025
POM_URL=https://github.com/mapp-digital/mapp-engage-android-v7

POM_LICENSE_NAME=MIT License
POM_LICENSE_URL=https://github.com/mapp-digital/mapp-engage-android-v7/blob/main/LICENSE.md
POM_LICENSE_DIST=repo

POM_SCM_URL=https://github.com/mapp-digital/mapp-engage-android-v7
POM_SCM_CONNECTION=scm:git:git://github.com/mapp-digital/mapp-engage-android-v7.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://git@github.com/mapp-digital/mapp-engage-android-v7.git

POM_DEVELOPER_ID=mapp
POM_DEVELOPER_NAME=Mapp Digital
POM_DEVELOPER_URL=https://github.com/mapp-digital/