VERSION=7.0.0-alpha01
ARTIFACT=engage-android
LIBRARY_NAME=engage-android
PUBLISHED_GROUP_ID=com.mapp
DEVELOPER_NAME=Mapp
LICENSE_URL=https://github.com/mapp-digital/mapp-engage-android-v7/blob/main/LICENSE.md
SITE_URL=https://mapp.com
LICENSE_NAME=MIT License
GIT_URL=https://github.com/mapp-digital/mapp-engage-android-v7
DEVELOPER_EMAIL=sekitafilovic@mapp.com
LIBRARY_DESCRIPTION=Mapp Engage Android SDK
DEVELOPER_ID=Mapp
POM_URL=https://github.com/mapp-digital/mapp-engage-android-v7
POM_SCM_URL=https://github.com/mapp-digital/mapp-engage-android-v7
POM_SCM_CONNECTION=scm:git:https://github.com/mapp-digital/mapp-engage-android-v7
POM_SCM_DEV_CONNECTION=scm:git:https://github.com/mapp-digital/mapp-engage-android-v7