name: Publish to Maven Central

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Debug directory
        run: |
          ls -R .

      - name: Write GPG key
        run: |
          mkdir -p mapp-engage-sdk
          echo "${{ secrets.SIGNING_KEY_ASC }}" | base64 --decode > mapp-engage-sdk/3F5AB862.asc

      - name: Create local.properties
        run: |
          echo "centralUsername=${{ secrets.CENTRAL_USERNAME }}" >> local.properties
          echo "centralPassword=${{ secrets.CENTRAL_PASSWORD }}" >> local.properties
          echo "signing.keyId=${{ secrets.SIGNING_KEY_ID }}" >> local.properties
          echo "signing.password=${{ secrets.SIGNING_KEY_PASSWORD }}" >> local.properties
          echo "signing.secretKeyRingFile=3F5AB862.asc" >> local.properties

      - name: Make gradle executable
        run: chmod +x gradlew

      - name: Publish to Maven Central
        run: |
          ./gradlew \
          :mapp-engage-sdk:clean \
          :mapp-engage-sdk:assembleProdRelease \
          :mapp-engage-sdk:publishMavenPublicationToMavenLocal \
          :mapp-engage-sdk:uploadToCentralPortal \
          -x :mapp-engage-sdk:testProdDebugUnitTest \
          -x :mapp-engage-sdk:testProdReleaseUnitTest \
          --stacktrace --no-daemon

