name: Publish to Maven Central

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Decode the signing key file
      - name: Write GPG key
        run: |
          echo "${{ secrets.SIGNING_KEY_ASC }}" | base64 --decode > 3F5AB862.asc

      # Write local.properties
      - name: Create local.properties
        run: |
          echo "signing.keyId=${{ secrets.SIGNING_KEY_ID }}" >> local.properties
          echo "signing.password=${{ secrets.SIGNING_KEY_PASSWORD }}" >> local.properties
          echo "signing.secretKeyRingFile=3F5AB862.asc" >> local.properties
          echo "mavenCentralUsername=${{ secrets.MAVEN_CENTRAL_USERNAME }}" >> local.properties
          echo "mavenCentralPassword=${{ secrets.MAVEN_CENTRAL_PASSWORD }}" >> local.properties

      - name: Make gradle executable
        run: chmod +x gradlew

      - name: Publish to Maven Central
        run: ./gradlew publishToCentralPortal --no-daemon --stacktrace

